-- Seed data for 20 Indian destinations
INSERT INTO destinations (slug, city, state, top_attractions, best_time, transport_summary, local_foods, seed_image_url) 
VALUES 
('jaipur-rajasthan', 'Jaipur', 'Rajasthan', 
 '["Amber Fort", "City Palace", "Hawa Mahal"]',
 'October to March (winter season)',
 'Well connected by air, rail, and road. Local transport via auto-rickshaws, taxis, and buses.',
 '["Dal Baati Churma", "Kachori", "Ghewar"]',
 '/images/destinations/jaipur.jpg'),

('udaipur-rajasthan', 'Udaipur', 'Rajasthan',
 '["City Palace", "Lake Pichola", "Jag Mandir"]',
 'October to March (pleasant weather)',
 'Airport and railway station available. Boat rides on lakes, auto-rickshaws for city travel.',
 '["Dal Baati", "Gatte ki Sabzi", "Malpua"]',
 '/images/destinations/udaipur.jpg'),

('goa-north', 'Goa', 'Goa',
 '["Baga Beach", "Old Goa Basilica", "Dudhsagar Falls"]',
 'November to February (dry season)',
 'Airport at Dabolim. Train connectivity. Bikes, taxis, and buses for local transport.',
 '["Fish Curry Rice", "Bebinca", "Vindaloo"]',
 '/images/destinations/goa.jpg'),

('varanasi-up', 'Varanasi', 'Uttar Pradesh',
 '["Ganges Ghats", "Kashi Vishwanath Temple", "Sarnath"]',
 'October to March (cooler months)',
 'Airport and major railway junction. Auto-rickshaws, cycle rickshaws, and boats.',
 '["Banarasi Paan", "Kachori Sabzi", "Malaiyo"]',
 '/images/destinations/varanasi.jpg'),

('agra-up', 'Agra', 'Uttar Pradesh',
 '["Taj Mahal", "Agra Fort", "Mehtab Bagh"]',
 'October to March (best weather)',
 'Well connected by air, rail, and road. Auto-rickshaws and taxis available.',
 '["Petha", "Bedai", "Paratha"]',
 '/images/destinations/agra.jpg'),

('delhi-ncr', 'Delhi', 'Delhi',
 '["Red Fort", "Qutub Minar", "Humayun''s Tomb"]',
 'October to March (winter season)',
 'Major transport hub with metro, buses, auto-rickshaws, and taxis.',
 '["Chole Bhature", "Paranthas", "Kulfi"]',
 '/images/destinations/delhi.jpg'),

('mumbai-maharashtra', 'Mumbai', 'Maharashtra',
 '["Gateway of India", "Marine Drive", "Elephanta Caves"]',
 'November to February (pleasant weather)',
 'Major airport and railway hub. Local trains, buses, taxis, and auto-rickshaws.',
 '["Vada Pav", "Pav Bhaji", "Bhel Puri"]',
 '/images/destinations/mumbai.jpg'),

('kolkata-wb', 'Kolkata', 'West Bengal',
 '["Victoria Memorial", "Howrah Bridge", "Dakshineswar Temple"]',
 'October to March (winter season)',
 'Airport and major railway junction. Metro, buses, trams, and taxis.',
 '["Macher Jhol", "Rosogolla", "Kathi Rolls"]',
 '/images/destinations/kolkata.jpg'),

('chennai-tn', 'Chennai', 'Tamil Nadu',
 '["Marina Beach", "Kapaleeshwarar Temple", "Mahabalipuram"]',
 'November to February (cooler months)',
 'Major airport and railway hub. Metro, buses, auto-rickshaws, and taxis.',
 '["Idli Sambar", "Filter Coffee", "Chettinad Cuisine"]',
 '/images/destinations/chennai.jpg'),

('bengaluru-karnataka', 'Bengaluru', 'Karnataka',
 '["Lalbagh Botanical Garden", "Cubbon Park", "Nandi Hills"]',
 'October to February (pleasant weather)',
 'Major IT hub with airport. Metro, buses, auto-rickshaws, and app-based cabs.',
 '["Masala Dosa", "Bisi Bele Bath", "Mysore Pak"]',
 '/images/destinations/bengaluru.jpg'),

('kochi-kerala', 'Kochi', 'Kerala',
 '["Fort Kochi", "Mattancherry Palace", "Chinese Fishing Nets"]',
 'October to March (dry season)',
 'Airport and railway station. Buses, auto-rickshaws, and ferry services.',
 '["Appam with Stew", "Karimeen Fish", "Puttu"]',
 '/images/destinations/kochi.jpg'),

('madurai-tn', 'Madurai', 'Tamil Nadu',
 '["Meenakshi Temple", "Thirumalai Nayakkar Palace", "Gandhi Memorial"]',
 'October to March (cooler months)',
 'Airport and railway connectivity. Buses and auto-rickshaws for local transport.',
 '["Jigarthanda", "Paruthi Paal", "Madurai Malli"]',
 '/images/destinations/madurai.jpg'),

('mysore-karnataka', 'Mysore', 'Karnataka',
 '["Mysore Palace", "Chamundi Hill", "Brindavan Gardens"]',
 'October to March (pleasant weather)',
 'Railway station and bus connectivity. Auto-rickshaws and taxis available.',
 '["Mysore Pak", "Masala Dosa", "Ragi Mudde"]',
 '/images/destinations/mysore.jpg'),

('ooty-tn', 'Ooty', 'Tamil Nadu',
 '["Botanical Gardens", "Doddabetta Peak", "Ooty Lake"]',
 'April to June, September to November (pleasant climate)',
 'Nearest airport at Coimbatore. Toy train and bus services. Taxis for local travel.',
 '["Nilgiri Tea", "Homemade Chocolates", "Varkey"]',
 '/images/destinations/ooty.jpg'),

('rishikesh-uttarakhand', 'Rishikesh', 'Uttarakhand',
 '["Laxman Jhula", "Beatles Ashram", "River Rafting"]',
 'March to June, September to November (ideal weather)',
 'Railway station at Haridwar (24km). Buses and taxis. Shared jeeps for local travel.',
 '["Chole Bhature", "Aloo Puri", "Herbal Tea"]',
 '/images/destinations/rishikesh.jpg'),

('leh-ladakh', 'Leh', 'Ladakh',
 '["Leh Palace", "Pangong Lake", "Nubra Valley"]',
 'May to September (accessible months)',
 'Airport with seasonal flights. Road access via Manali/Srinagar. Local taxis and bikes.',
 '["Thukpa", "Momos", "Butter Tea"]',
 '/images/destinations/leh.jpg'),

('amritsar-punjab', 'Amritsar', 'Punjab',
 '["Golden Temple", "Jallianwala Bagh", "Wagah Border"]',
 'October to March (pleasant weather)',
 'Airport and railway connectivity. Auto-rickshaws, buses, and taxis.',
 '["Amritsari Kulcha", "Lassi", "Makki di Roti"]',
 '/images/destinations/amritsar.jpg'),

('hyderabad-telangana', 'Hyderabad', 'Telangana',
 '["Charminar", "Golconda Fort", "Ramoji Film City"]',
 'October to February (cooler months)',
 'Major airport and railway hub. Metro, buses, auto-rickshaws, and app-based cabs.',
 '["Hyderabadi Biryani", "Haleem", "Qubani ka Meetha"]',
 '/images/destinations/hyderabad.jpg'),

('pune-maharashtra', 'Pune', 'Maharashtra',
 '["Shaniwar Wada", "Sinhagad Fort", "Osho Ashram"]',
 'October to February (pleasant weather)',
 'Airport and railway connectivity. Buses, auto-rickshaws, and app-based cabs.',
 '["Misal Pav", "Puran Poli", "Solkadhi"]',
 '/images/destinations/pune.jpg'),

('shimla-hp', 'Shimla', 'Himachal Pradesh',
 '["Mall Road", "Jakhu Temple", "Kufri"]',
 'March to June, September to November (pleasant weather)',
 'Toy train from Kalka. Bus services from major cities. Taxis for local travel.',
 '["Himachali Thali", "Chana Madra", "Patande"]',
 '/images/destinations/shimla.jpg');
