import {
  Loader2,
  ChevronLeft,
  LogIn,
  Mail,
  Github,
  User,
  LogOut,
  Settings,
  Home,
  MapPin,
  BookMarked,
  Compass,
  ArrowLeft,
  ChevronRight,
  Plus,
  Trash2,
  Edit2,
  Calendar,
  Clock,
  Map,
  Search,
  X,
  Check,
  AlertCircle,
  Info,
  ExternalLink,
  Download,
  Share2,
  Menu,
  Star,
  Heart,
  Filter,
  SlidersHorizontal,
  MoreHorizontal,
  CheckCircle2,
  XCircle,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  ArrowUpDown,
  ArrowUpRight,
  ArrowRight,
  ArrowDown,
  PlusCircle,
  MinusCircle,
  HelpCircle,
  Sun,
  Moon,
  Laptop,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  MessageSquare,
  Phone,
  Mail as MailIcon,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin,
  Globe,
  Map as MapIcon,
  Navigation,
  Compass as CompassIcon,
  Camera,
  Image,
  FileText,
  Download as DownloadIcon,
  Upload,
  Printer,
  CreditCard,
  DollarSign,
  ShoppingCart,
  Package,
  Tag,
  Percent,
  Bell,
  BellOff,
  UserCheck,
  Users,
  UserPlus,
  UserX,
  Settings as SettingsIcon,
  Sliders,
  LayoutDashboard,
  BarChart2,
  PieChart,
  LineChart,
  Activity,
  TrendingUp,
  TrendingDown,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarClock,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock10,
  Clock11,
  Clock12,
  Clock1,
  Clock2,
  type LucideIcon,
} from 'lucide-react';

export const Icons: { [key: string]: LucideIcon } = {
  // UI
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  arrowUpDown: ArrowUpDown,
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  plus: Plus,
  plusCircle: PlusCircle,
  minusCircle: MinusCircle,
  x: X,
  check: Check,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  externalLink: ExternalLink,
  download: Download,
  downloadCloud: DownloadIcon,
  upload: Upload,
  printer: Printer,
  filter: Filter,
  sliders: SlidersHorizontal,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  messageSquare: MessageSquare,
  phone: Phone,
  mail: MailIcon,
  star: Star,
  heart: Heart,
  trash: Trash2,
  edit: Edit2,
  search: Search,
  
  // Navigation
  home: Home,
  mapPin: MapPin,
  map: MapIcon,
  navigation: Navigation,
  compass: CompassIcon,
  globe: Globe,
  
  // Media
  camera: Camera,
  image: Image,
  fileText: FileText,
  
  // Commerce
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  package: Package,
  tag: Tag,
  percent: Percent,
  
  // Auth
  login: LogIn,
  logout: LogOut,
  user: User,
  userCheck: UserCheck,
  userPlus: UserPlus,
  userX: UserX,
  users: Users,
  
  // Social
  gitHub: Github,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  
  // Time & Date
  calendar: CalendarIcon,
  calendarDays: CalendarDays,
  calendarCheck: CalendarCheck,
  calendarX: CalendarX,
  calendarClock: CalendarClock,
  clock: ClockIcon,
  clock3: Clock3,
  clock4: Clock4,
  clock5: Clock5,
  clock6: Clock6,
  clock7: Clock7,
  clock8: Clock8,
  clock9: Clock9,
  clock10: Clock10,
  clock11: Clock11,
  clock12: Clock12,
  clock1: Clock1,
  clock2: Clock2,
  
  // Custom
  compassIcon: Compass,
  bookMarked: BookMarked,
  arrowLeft: ArrowLeft,
  share: Share2,
  bell: Bell,
  bellOff: BellOff,
  settings2: SettingsIcon,
  layoutDashboard: LayoutDashboard,
  barChart: BarChart2,
  pieChart: PieChart,
  lineChart: LineChart,
  activity: Activity,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
};
