import {
  Home,
  Bookmark,
  Compass,
  Menu,
  User,
  Search,
  X,
  Settings,
  LogOut,
  LogIn,
  ChevronLeft,
  ChevronRight,
  LoaderCircle,
  Github,
  Chrome,
  Mail,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  home: Home,
  bookmark: Bookmark,
  compass: Compass,
  menu: Menu,
  user: User,
  search: Search,
  close: X,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  spinner: LoaderCircle,
  gitHub: Github,
  google: Chrome,
  mail: Mail,
};
